### PR TITLE
ubuntu-16.04: fix php fpm configuration and install roundcube webmail if choosen

### PR DESCRIPTION
**Pull request by erikcas**

### CODE REVIEW

**Comment by servisys** [comment]
But squirrelmail is working?

**Comment by erikcas** [comment]
better question is, is squirrelmail supported on ispconfig (3.1)? I cannot find it in current tutorials, for both apache and nginx variants

**Comment by servisys** [comment]
Yeah, it shoul work. Got to test

**Comment by erikcas** [comment]
hmm will do some checking on squirrelmail in the weekend

**Comment by servisys** [comment]
i'll wait some feedback about squirrel mail, before merge.

Thank you!

**Comment by erikcas** [comment]
hi, that squirrelmail is a no go area for me

**Comment by schliflo** [comment]
the squirrel is on it's way
 giphy

**Comment by servisys** [comment]
Yeah.. it seems nearly dead project... Someone can confirm?

**Comment by wolv-dev** [comment]
Last update on squirrelmail:

ANNOUNCE: PHP 5.4 & 5.5 Compatibility
May 30, 2013 by Paul Lesniewski

**Pull request closed without merging**
