### PR TITLE
 Added support for Raspbian, updated packages, output and added Travis CI.

### LINKED ISSUE #257: Metronom -> Metronome
It is possible to resolve the mistake in all codes + the name of the files?

### PR DESCRIPTION
**Pull request by tdulcet**
- Added supported software table and updated Readme.
  - Copy edited Readme.
- Added support for Raspbian 7, 8 and 9. #251/#204/#167/#74 
  - Reverts #226, which did not add all the required scripts. The scripts added were just [a copy from Ubuntu 16.04](https://github.com/servisys/ispconfig_setup/blob/master/distros/raspbian9/askquestions.sh#L2), but Raspbian is based on Debian.
  - Disabled HHVM on Raspbian.
- Updated script formatting. #210
- Added more checks and removed duplicate code.
- Determined IP address.
- Allow user to update hostname and output warning if it is not a valid FQDN. #144 and #61
- Output more system information (for debugging).
- Updated Jailkit scripts.  #232
  - Checks the md5sum after downloading to the one [provided on Jailkit's website](https://olivier.sessink.nl/jailkit/index.html#download).
- Updated Quota scripts.
  - Only add quota to root partition.
  - Fixed [issue](https://www.howtoforge.com/community/threads/new-install-jessie-issue-with-quota.71183/#post-342624) for Debian/Raspbian.
- Updated packages to be consistent with the HowtoForge [The Perfect Server tutorials](https://www.ispconfig.org/documentation/).
  - Added Postgrey to Debian 8 and Ubuntu 16.10.
  - Added UFW to Debian 8, Ubuntu 16.10 and 18.04.
  - Added rkhunter to Ubuntu 16.04.
  - Added Webalizer to CentOS 7.
  - Added Let's Encrypt to Ubuntu 16.10.
- Added OpenDMARC to Debian/Raspbian and Ubuntu
- Updated output.
  - Hides output of package managers and other commands unless they returns a nonzero exit code instead of just redirecting the output to `/dev/null` (for debugging).
  - Output the default ISPConfig Username and Password. #205 and #198
  - Fixed #257 for the output.
  - Copy edited output.
- Updated questions to require at least one nonwhitespace character for input.
- Added Travis CI. See the logs [here](https://travis-ci.org/tdulcet/ispconfig_setup).
  - Need to enable at [travis-ci.org](https://travis-ci.org/) before merging this pull request.
  - Runs every possible combination of MySQL/MariaDB, Apache/nginx and Dovecot/Courier.
  - Now possible to use this script noninteractively. See the [Travis CI file](https://github.com/tdulcet/ispconfig_setup/blob/master/.travis.yml#L31) for more info. #185
- Fixed numerous bugs found by [ShellCheck](https://www.shellcheck.net/).
- Fixed numerous other bugs/issues. #236/#179, #234,  (the rest of) #92/#87, etc.
  - Set the time zone for nginx to the user's time zone.
  - Copied the fixes from Debian 8/9's `install_ispconfig.sh` to the other distributions.
- Output error/warning for issues #67, #68, #69, #70, #176 and #179.
- Ready for future support of Ubuntu 17.10, openSUSE Leap and Fedora, which are supported by ISPConfig.

Test with the following command:
```shell
cd /tmp; wget -O installer.tgz "https://github.com/tdulcet/ispconfig_setup/tarball/master"; tar zxvf installer.tgz; cd *ispconfig*; sudo bash install.sh
```

### CODE REVIEW

**Comment by servisys** [comment]
Thank you, i'll take a look for merge soon :)

**Comment by servisys** [comment]
Why replaced all apt-get install (or similar) with apt_install (wich is not a command)?

**Comment by servisys** [comment]
Oh wtf, i was serching for the function, now i've seen it!
Thank you, very great work, was really needed :)

**Comment by schliflo** [comment]
Hey @servisys I guess you still need to setup Travis CI, right? Currently there are no tests running as the project does not exist: https://travis-ci.org/servisys/ispconfig_setup

**Comment by tdulcet** [comment]
Yeah, you need to sign in at travis-ci.org and enable it for this repository.

Also, it seems that these issues:  #67, #68, #69, #70, #176 and #179 were automatically closed because I mentioned them in the pull request, but I did not actually resolve them...

**Comment by tdulcet** [comment]
@servisys I am not sure why you made this change: https://github.com/servisys/ispconfig_setup/commit/f0e808aa40de3ab9569efc642357bc3214b067d1#diff-3fbb47e318cd8802bd325e7da9aaabe8

The HowtoForge The Perfect Server tutorials state the hostname file should just contain the subdomain part of the FQDN: https://www.howtoforge.com/tutorial/perfect-server-debian-9-stretch-apache-bind-dovecot-ispconfig-3-1/#-configure-thenbsphostname

**Comment by schliflo** [comment]
@servisys you still need to setup travis CI to get the tests running. Let me know if you need help.

**Comment by servisys** [comment]
Sorry... but what are you talking about?

**Comment by schliflo** [comment]
Idk what you did, but the build badge on top of the readme still says unknown:
screenshot 2018-10-04 at 17 14 02
And https://travis-ci.org/servisys/ispconfig_setup still is not found, so i guess that probably went wrong :/

**Comment by tdulcet** [comment]
You may have to wait until the first commit after it was enabled for the link to work.

**Comment by schliflo** [comment]
@tdulcet you're correct. Seems to be working now: https://travis-ci.org/servisys/ispconfig_setup/builds/437483820 :) Nice!

**Pull request merged**
