### PR TITLE
[DONOTMERGE]Ubuntu 18.04

### PR DESCRIPTION
**Pull request by erikcas**
Ubuntu-18.04 support. Tested on raspi pi3B with nginx

EDIT: apache variant needs love. Will check and test upcoming weekend

### CODE REVIEW

**Comment by erikcas** [comment]
@robinvandernoord can you please test? I see you also did some on ubuntu-18.04 install

**Comment by erikcas** [comment]
did you apply the patches? for 18.04 every reference to php7.0 is replaced by 7.2.

else try installing from my repo directly: https://github.com/erikcas/ispconfig_setup/tree/ubuntu-18.04
this pull request comes from that branch

it works flawless on my end

**Comment by n0v3xx** [comment]
I tried it on the fresh ubuntu 18.04 root server from kimsufi. I used this command, its your branch.

`cd /tmp; wget --no-check-certificate -O installer.tgz "https://github.com/erikcas/ispconfig_setup/tarball/master"; tar zxvf installer.tgz; cd *ispconfig*; bash install.sh`

I dont know why it use the wrong php fpm version :(
I fixed the issues manually and it works

**Comment by n0v3xx** [comment]
Oh.... i used the master not the 18.04 branch -,-
Ok i think thats the problem, your code works.

**Comment by erikcas** [comment]
apache needs some love, doesn't seem to work

**Comment by Neustradamus** [comment]
Any news?

**Comment by servisys** [comment]
Just relased 18.04 version, need test :P

**Comment by gOOvER** [comment]
@servisys remove mcrypt. It's not longer aviable since php 7.1

**Comment by n0v3xx** [comment]
@gOOvER that is wrong. Mcrypt is available in 7.1 !

Warnung
This feature was DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0.

**Comment by gOOvER** [comment]
And which PHP Version Ubuntu 18.04 use ;)

**Pull request closed without merging**
