### PR TITLE
Bring in some Colour :)

### PR DESCRIPTION
**Pull request by gOOvER**
Bring in some Colour :)  ... atm only for "done!"

### CODE REVIEW

**Comment by servisys** [comment]
Thank you for help me, only a thing, for changes use the latest version in developing (v.1.0.5 right now).

So we merge it in master after some tests :)

**Comment by gOOvER** [comment]
Ah ok... i only know Master for Develop and Tags for Releasings....... Maybe it's better to follow the normal way. So it's not confusing :)

**Comment by gOOvER** [comment]
I'll added you to Skype ...... :)

**Comment by servisys** [comment]
Oh sorry, i'm a bit new to git, my fault so ;)

**Pull request merged**
