### PR TITLE
Lot of Fixes for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by gOOvER**
A lot of fixes for Ubuntu. I disabled Webmail Install, because this mus be rewritten for Ubuntu 16.04.

Also a lot of Steps missing form Perfect Server Setup for Ubuntu 16.04

Maybe more fixes musst be added

### CODE REVIEW

**Comment by carras** [comment]
Why do you use "install letsencrypt" instead of "certbot"?

**Comment by gOOvER** [comment]
This is the official from Ubuntu Perfect Server Setup .... ;)

2017-02-03 19:37 GMT+01:00 carras <notifications@github.com>:

**Comment by carras** [comment]
Ok, It's true. I think before was the order way.

**Comment by carras** [comment]
I have a server running with the previous version of this scripts (I managed to make it work, go figure...) obviously on Ubuntu 16.04, do you recommend me to do any changes? Could I execute the script in case something is missing? I sorry to bother you.

**Pull request merged**
