### PR TITLE
Added php5-fpm and cURL to install

### PR DESCRIPTION
**Pull request by gOOvER**

### CODE REVIEW

**Comment by gOOvER** [comment]
php5-mysql ist an Old one. php5-mysql ist the better Interface for MySQL. The Perfect Server Setup is not really up2date. Also php5-ps und php5-ming are not longer present with php 5.6.

atm i install with mysqlnd

**Comment by gOOvER** [comment]
See also here:
http://serverfault.com/questions/400434/php-mysqlnd-or-php-mysql

**Comment by gOOvER** [comment]
PHP 5.4 has mysqlnd as default
As of PHP 5.4, the mysqlnd library is a php.net compile time default to all PHP MySQL extensions. Also, the php.net Windows team is using mysqlnd for the official PHP Windows distribution since mysqlnd became available in PHP 5.3.

Advantages of using mysqlnd
The mysqlnd library is highly optimized for and tightly integrated into PHP. The MySQL Client Library cannot offer the same optimizations because it is a general-purpose client library.

The mysqlnd library is using PHP internal C infrastructure for seamless integration into PHP. In addition, it is using PHP memory management, PHP Streams (I/O abstraction) and PHP string handling routines. The use of PHP memory management by mysqlnd allows, for example, memory savings by using read-only variables (copy on write) and makes mysqlnd apply to PHP memory limits. Additional advantages include:

Powerful plugin API to extend feature set
Asynchronous, non-blocking queries
150+ performance statistics
Ships together with the PHP 5.3, and later, source
No need to install MySQL Client Library
Powerful plugins. See Below.

**Comment by servisys** [comment]
Ok, thank you for fix.

I'll merge it ;)

**Pull request merged**
