### PR TITLE
Added root check, Changed /etc/init.d  to service, some More Fixes

### PR DESCRIPTION
**Pull request by gOOvER**
* Added root check
* Changed /etc/init.d  to service
* some More Fixes
* Added Variable for Jailkit, because a really Old Version was used. You can set Version in Global Variables

### CODE REVIEW

**Comment by gOOvER** [comment]
Please wait with merging... Must find a Bug in Jailkit Installation

**Comment by servisys** [comment]
Should be useful to create a "devel" branch to implement new feature and let master as last stable release?

**Comment by gOOvER** [comment]
This would be great :)

**Comment by servisys** [comment]
Ok, finish your changes, then we marge with actual master. Or another idea whoudl be create a new version (v.1.0.6 for example) as pre-relase.

When it's ready we tag as "relase" and merge with master. 

What do you think?

**Comment by gOOvER** [comment]
I think, i found the Bug...

The Master is Pe Release :)

**Comment by servisys** [comment]
Nice ;)

I'll merge some fix cuased by "!" in echoes and then we start working on v.1.0.6 with pre-relase :dancer:

**Pull request merged**
