### PR TITLE
add php5

### PR DESCRIPTION
**Pull request by vittore**

### CODE REVIEW

**Comment by servisys** [comment]
Thank you!

**Comment by gOOvER** [comment]
I don't see the sense to install php5. This will be done at apach2 install

**Comment by servisys** [comment]
No that's the problem.

Look at

apt-get install apache2
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
I seguenti pacchetti saranno inoltre installati:
  apache2-bin apache2-data apache2-utils libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.1-0
Pacchetti suggeriti:
  apache2-doc apache2-suexec-pristine apache2-suexec-custom
I seguenti pacchetti NUOVI saranno installati:
  apache2 apache2-bin apache2-data apache2-utils libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.1-0
0 aggiornati, 9 installati, 0 da rimuovere e 3 non aggiornati.
È necessario scaricare 1.541 kB di archivi.
Dopo quest'operazione, verranno occupati 6.358 kB di spazio su disco.
Continuare? [S/n] 

We found the problem on Debian 8. In any case an install of php5 is workless ;)

**Comment by vittore** [comment]
Correct. But install need php-cli at line 70 of
distros/debian8/install_ispconfig.sh
due "command not found" error.

v.


2015-07-14 15:23 GMT+02:00 Torsten Widmann <notifications@github.com>:

> I don't see the sense to install php5. This will be done at apach2 install
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/servisys/ispconfig_setup/pull/57#issuecomment-121236452>
> .
>



-- 
http://www.zen.pn.it

**Comment by gOOvER** [comment]
php5-cli  ;)

**Comment by vittore** [comment]
Ops! Yes. I change the code :) and make a PR

v.


2015-07-14 16:06 GMT+02:00 Torsten Widmann <notifications@github.com>:

> php5-cli ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/servisys/ispconfig_setup/pull/57#issuecomment-121248517>
> .
>



-- 
http://www.zen.pn.it

**Pull request merged**
